### ISSUE TITLE
Fail to load CH4_Kazakov_without_NOx.yaml in PSR.jl 

### ISSUE THREAD

**Issue by dimaZloy** [DENG-MIT/Arrhenius.jl#78] opened 2021-05-22 14:30 UTC
hi, 

I try just to compile the PSR.jl resulting in the error below. Can you recompile the DRM22 mech (CH4_Kazakov_without_NOx.yaml) / or fix it ? 

Thanks, Dmitry 

julia> gas = CreateSolution("CH4_Kazakov_without_NOx.yaml")
ERROR: MethodError: no method matching Array{Float64,2}(::Array{Float64,3})
Closest candidates are:
  Array{Float64,2}(::AbstractArray{S,N}) where {T, N, S} at array.jl:562
  Array{Float64,2}(::UndefInitializer, ::Int64, ::Int64) where T at boot.jl:408
  Array{Float64,2}(::UndefInitializer, ::Int64...) where {T, N} at boot.jl:412
  ...
Stacktrace:
 [1] convert(::Type{Array{Float64,2}}, ::Array{Float64,3}) at .\array.jl:554
 [2] Arrhenius.Transport(::Int64, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,3}) at C:\Users\lysenkod\.julia\packages\Arrhenius\BOKjU\src\DataStructure.jl:23
 [3] CreateSolution(::String) at C:\Users\lysenkod\.julia\packages\Arrhenius\BOKjU\src\Solution.jl:142
 [4] top-level scope at REPL[31]:1

**Comment by jiweiqi** [comment] 2021-05-22 16:40
Hi @dimaZloy , I transferred this issue to Arrhenius.jl for better organization as the issue is in the core parts of Arrhenius.jl

**Comment by dimaZloy** [comment] 2021-05-23 09:43
hi @jiweiqi 
Ok, it works now.

**Closed** 2021-05-24 11:12 UTC
Labels: bug
